// Generated by packages/public-sync — do not edit here.
//
// Edit packages/public-sync/stage.mjs in the source repo, not this file.

/** Where the API lives, unless overridden. */
export const DEFAULT_BASE_URL = "https://sendandretain.com";

/** Every key starts with this. Checked locally so a typo fails before a round-trip. */
export const API_KEY_PREFIX = "aem_";

export const API_KEY_ENV_VAR = "SENDANDRETAIN_API_KEY";
export const BASE_URL_ENV_VAR = "SENDANDRETAIN_BASE_URL";

/**
 * Read an env var without assuming a Node runtime.
 *
 * The SDK is ESM and runs on edge and worker runtimes where \`process\` is not
 * defined at all — an unguarded \`process.env\` there is a ReferenceError at
 * import time, not a missing value.
 */
function env(name: string): string | undefined {
  return typeof process !== "undefined" ? process.env?.[name] : undefined;
}

/**
 * Resolve and validate the API key.
 *
 * Throws on a missing or wrong-shaped key, which is the ONE thing these SDKs
 * throw for. Every API failure comes back as a value — see the \`{ data, error }\`
 * union each method returns.
 */
export function resolveApiKey(explicit?: string): string {
  const key = explicit ?? env(API_KEY_ENV_VAR);
  if (!key) {
    throw new Error(
      `Missing API key. Pass createClient({ apiKey }) or set ${API_KEY_ENV_VAR}.`
    );
  }
  if (!key.startsWith(API_KEY_PREFIX)) {
    throw new Error(
      `${brandName} API keys start with "${API_KEY_PREFIX}"; got "${key.slice(0, 8)}…". ` +
        "A key from another surface (or another product) will only ever 401."
    );
  }
  return key;
}

const brandName = "Send & Retain";

export function resolveBaseUrl(explicit?: string): string {
  return (explicit ?? env(BASE_URL_ENV_VAR) ?? DEFAULT_BASE_URL).replace(/\/+$/, "");
}

/** Identifies the client in our logs. Matches the other SDKs' format. */
export function userAgent(version: string): string {
  return `sendandretain-node:${version}`;
}

/**
 * Default request timeout.
 *
 * There was none: a hung connection hung the caller's process forever, because
 * the platform \`fetch\` has no default. One minute is the Go SDK convention and
 * is far above any real call here.
 */
export const DEFAULT_TIMEOUT_MS = 60_000;

/** Longest \`Idempotency-Key\` the API accepts. Longer is rejected, never truncated. */
export const MAX_IDEMPOTENCY_KEY_LENGTH = 256;

export interface RequestOptions {
  /**
   * Replay protection for a request you might retry. A retry with the same key
   * returns the original result instead of doing the work twice. Keys are
   * namespaced per endpoint, so the same string sent to two endpoints is two
   * different requests.
   */
  idempotencyKey?: string;
}

/** \`Idempotency-Key\` header params, or undefined when no key was given. */
export function idempotency(options?: RequestOptions) {
  const key = options?.idempotencyKey;
  if (!key) return undefined;
  if (key.length > MAX_IDEMPOTENCY_KEY_LENGTH) {
    throw new Error(
      `Idempotency-Key must be ${MAX_IDEMPOTENCY_KEY_LENGTH} characters or fewer. ` +
        "A truncated key collides with every other key sharing its prefix, so this " +
        "throws rather than trimming."
    );
  }
  return { header: { "Idempotency-Key": key } };
}

export interface RateLimit {
  /** Requests allowed per window. */
  limit: number;
  /** Requests left in this window. */
  remaining: number;
  /** Raw \`RateLimit-Policy\`, e.g. \`120;w=60\`. */
  policy: string | null;
  /** Only on a 429. Milliseconds to wait. */
  retryAfterMs: number | null;
}

/**
 * Read the rate-limit headers off any response — success OR error.
 *
 * They are on both because the API attaches them at a single choke point. A
 * client backing off after a 429 needs them at least as much as one that
 * succeeded, and this is the ergonomic that makes them reachable without
 * narrowing the result union first.
 *
 * NOTE: the limit is a best-effort backstop against runaway loops, not a quota.
 * It is enforced per server instance, so the real ceiling across a scaled
 * deployment is higher than the advertised number. Do not build a scheduler
 * that assumes otherwise.
 */
export function rateLimit(response: Response | undefined): RateLimit | null {
  if (!response) return null;
  const limit = Number(response.headers.get("RateLimit-Limit"));
  if (!Number.isFinite(limit)) return null;
  const retryAfter = Number(response.headers.get("Retry-After"));
  return {
    limit,
    remaining: Number(response.headers.get("RateLimit-Remaining")) || 0,
    policy: response.headers.get("RateLimit-Policy"),
    retryAfterMs: Number.isFinite(retryAfter) && retryAfter > 0 ? retryAfter * 1000 : null,
  };
}

/**
 * The request id the API stamped on this response.
 *
 * Quote it in a support request — it is the only handle that ties what you saw
 * to what we logged. Errors also carry it in the body as \`request_id\`.
 */
export function requestId(response: Response | undefined): string | null {
  return response?.headers.get("X-Request-Id") ?? null;
}

/**
 * What to try when a request fails, keyed by the error code.
 *
 * Exists because "invalid_request" alone sends a developer to the wrong place.
 * Codes not listed here get null rather than a guess.
 */
export function suggestedAction(code: string): string | null {
  switch (code) {
    case "unauthorized":
      return `Check the key is current and starts with "${API_KEY_PREFIX}". Mint a new one in the dashboard if it was revoked.`;
    case "forbidden":
      return "The key is valid but its scope is too low. The error body carries required_scope and key_scope — mint a key at that tier.";
    case "not_found":
      return "Check the id, and that the key can reach that project — an org-scoped key may be limited to a subset.";
    case "rate_limited":
      return "Back off for retryAfterMs from rateLimit(response), then retry.";
    case "conflict":
      return "Something changed underneath this call. Re-read the resource and decide again.";
    case "invalid_request":
      return "The message names the offending field. Nothing was changed, so it is safe to fix and resend.";
    case "upstream_error":
      return "A provider we depend on failed. Safe to retry with backoff; pass an idempotencyKey so a retry cannot double-apply.";
    case "internal":
      return "Our fault. Quote requestId(response) in a support request.";
    default:
      return null;
  }
}

/** Timeout signal, merged with any caller-supplied signal. */
export function timeoutSignal(timeoutMs = DEFAULT_TIMEOUT_MS): AbortSignal {
  return AbortSignal.timeout(timeoutMs);
}
// ── Transport ──────────────────────────────────────────────────────────────
//
// A `fetch` that every request goes through: auth, User-Agent, timeout,
// retries and idempotency, decided once here rather than per method.

/** Default number of RETRIES (so up to three attempts in all). */
export const DEFAULT_MAX_RETRIES = 2;

const RETRYABLE_STATUS = new Set([408, 429, 500, 502, 503, 504]);
const IDEMPOTENT_METHODS = new Set(["GET", "HEAD", "OPTIONS", "PUT", "DELETE"]);
/** 429s that are a sending QUOTA, not a throttle: waiting a second changes nothing. */
const QUOTA_CODES = new Set(["daily_cap", "monthly_cap"]);

export interface TransportOptions {
  apiKey: string;
  /** The SDK's own version, for the User-Agent. */
  version: string;
  /** Retries on 408/429/5xx and network errors. 0 disables. */
  maxRetries?: number;
  /** Per-attempt timeout. */
  timeoutMs?: number;
  /** Bring your own fetch (tests, proxies). Defaults to the global one. */
  fetch?: typeof fetch;
}

function newIdempotencyKey(): string {
  const c = (globalThis as { crypto?: { randomUUID?: () => string } }).crypto;
  if (c?.randomUUID) return c.randomUUID();
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}-${Math.random().toString(36).slice(2)}`;
}

/**
 * Milliseconds to wait before retry number `attempt` (1-based).
 *
 * `Retry-After` wins when the server sent one. Otherwise exponential backoff
 * from 500ms, capped at 8s, with full jitter so a fleet of clients that failed
 * together does not retry together.
 */
export function backoffMs(attempt: number, retryAfter: string | null): number {
  const seconds = retryAfter === null ? NaN : Number(retryAfter);
  if (Number.isFinite(seconds) && seconds >= 0) return Math.min(seconds * 1000, 60_000);
  const ceiling = Math.min(500 * 2 ** (attempt - 1), 8_000);
  return Math.round(ceiling / 2 + Math.random() * (ceiling / 2));
}

const sleep = (ms: number, signal?: AbortSignal | null) =>
  new Promise<void>((resolve, reject) => {
    if (signal?.aborted) return reject(signal.reason);
    const timer = setTimeout(resolve, ms);
    signal?.addEventListener(
      "abort",
      () => {
        clearTimeout(timer);
        reject(signal.reason);
      },
      { once: true }
    );
  });

async function isQuota(response: Response): Promise<boolean> {
  if (response.status !== 429) return false;
  try {
    const body = (await response.clone().json()) as { error?: { code?: string } };
    return QUOTA_CODES.has(body?.error?.code ?? "");
  } catch {
    return false;
  }
}

/**
 * Build the fetch every SDK method uses.
 *
 * - **Retries are only ever safe ones.** A GET/PUT/DELETE, or a POST carrying an
 *   `Idempotency-Key`. Every POST gets a generated key when the caller did not
 *   pass one, so a retried create can never run twice — the API replays the
 *   first result instead.
 * - **A quota is not a throttle.** A 429 `daily_cap` / `monthly_cap` is
 *   returned at once; retrying it only burns the caller's time.
 * - **The caller's signal still wins.** Aborting cancels the attempt in flight
 *   and any wait between attempts.
 */
export function createTransport(options: TransportOptions): typeof fetch {
  const baseFetch = options.fetch ?? globalThis.fetch;
  const maxRetries = Math.max(0, options.maxRetries ?? DEFAULT_MAX_RETRIES);
  const timeoutMs = options.timeoutMs ?? DEFAULT_TIMEOUT_MS;
  const ua = userAgent(options.version);

  return async (input, init) => {
    const original = new Request(input, init);
    const headers = new Headers(original.headers);
    headers.set("Authorization", `Bearer ${options.apiKey}`);
    if (!headers.has("User-Agent")) headers.set("User-Agent", ua);
    if (original.method === "POST" && maxRetries > 0 && !headers.has("Idempotency-Key")) {
      headers.set("Idempotency-Key", newIdempotencyKey());
    }
    const template = new Request(original, { headers });
    const retryable = IDEMPOTENT_METHODS.has(template.method) || headers.has("Idempotency-Key");

    for (let attempt = 0; ; attempt++) {
      const signals = [
        AbortSignal.timeout(timeoutMs),
        ...(original.signal ? [original.signal] : []),
      ];
      const signal = signals.length > 1 ? AbortSignal.any(signals) : signals[0]!;
      try {
        const response = await baseFetch(new Request(template.clone(), { signal }));
        const again =
          retryable &&
          attempt < maxRetries &&
          RETRYABLE_STATUS.has(response.status) &&
          !(await isQuota(response));
        if (!again) return response;
        await sleep(backoffMs(attempt + 1, response.headers.get("Retry-After")), original.signal);
      } catch (error) {
        // The caller aborted: stop now, whatever the budget says.
        if (original.signal?.aborted) throw error;
        if (!retryable || attempt >= maxRetries) throw error;
        await sleep(backoffMs(attempt + 1, null), original.signal);
      }
    }
  };
}

// ── Pagination ─────────────────────────────────────────────────────────────

/** The list envelope every collection answers. */
export interface ListPage<T> {
  object: "list";
  data: T[];
  has_more: boolean;
  next_cursor: string | null;
}

/**
 * Walk every page of a list, yielding rows.
 *
 * `fetchPage` is handed the cursor for the next page (undefined for the first)
 * and returns the SDK's usual `{ data, error }`. An error mid-walk throws —
 * an iterator has no other channel — carrying the API's error object.
 */
export async function* paginate<T>(
  fetchPage: (cursor: string | undefined) => Promise<{ data?: ListPage<T>; error?: unknown }>
): AsyncGenerator<T, void, undefined> {
  let cursor: string | undefined;
  for (;;) {
    const { data, error } = await fetchPage(cursor);
    if (error || !data) {
      throw Object.assign(new Error("List request failed while paginating."), { error });
    }
    yield* data.data;
    if (!data.has_more || !data.next_cursor) return;
    cursor = data.next_cursor;
  }
}
