// Generated by packages/public-sync — do not edit here.
//
// Edit packages/public-sync/stage.mjs in the source repo, not this file.

/** Where the API lives, unless overridden. */
export const DEFAULT_BASE_URL = "https://sendandretain.com";

/** Every key starts with this. Checked locally so a typo fails before a round-trip. */
export const API_KEY_PREFIX = "aem_";

export const API_KEY_ENV_VAR = "SENDANDRETAIN_API_KEY";
export const BASE_URL_ENV_VAR = "SENDANDRETAIN_BASE_URL";

/**
 * Read an env var without assuming a Node runtime.
 *
 * The SDK is ESM and runs on edge and worker runtimes where \`process\` is not
 * defined at all — an unguarded \`process.env\` there is a ReferenceError at
 * import time, not a missing value.
 */
function env(name: string): string | undefined {
  return typeof process !== "undefined" ? process.env?.[name] : undefined;
}

/**
 * Resolve and validate the API key.
 *
 * Throws on a missing or wrong-shaped key, which is the ONE thing these SDKs
 * throw for. Every API failure comes back as a value — see the \`{ data, error }\`
 * union each method returns.
 */
export function resolveApiKey(explicit?: string): string {
  const key = explicit ?? env(API_KEY_ENV_VAR);
  if (!key) {
    throw new Error(
      `Missing API key. Pass createClient({ apiKey }) or set ${API_KEY_ENV_VAR}.`
    );
  }
  if (!key.startsWith(API_KEY_PREFIX)) {
    throw new Error(
      `${brandName} API keys start with "${API_KEY_PREFIX}"; got "${key.slice(0, 8)}…". ` +
        "A key from another surface (or another product) will only ever 401."
    );
  }
  return key;
}

const brandName = "Send & Retain";

export function resolveBaseUrl(explicit?: string): string {
  return (explicit ?? env(BASE_URL_ENV_VAR) ?? DEFAULT_BASE_URL).replace(/\/+$/, "");
}

/** Identifies the client in our logs. Matches the other SDKs' format. */
export function userAgent(version: string): string {
  return `sendandretain-node:${version}`;
}

/**
 * Default request timeout.
 *
 * There was none: a hung connection hung the caller's process forever, because
 * the platform \`fetch\` has no default. One minute is the Go SDK convention and
 * is far above any real call here.
 */
export const DEFAULT_TIMEOUT_MS = 60_000;

/** Longest \`Idempotency-Key\` the API accepts. Longer is rejected, never truncated. */
export const MAX_IDEMPOTENCY_KEY_LENGTH = 256;

export interface RequestOptions {
  /**
   * Replay protection for a request you might retry. A retry with the same key
   * returns the original result instead of doing the work twice. Keys are
   * namespaced per endpoint, so the same string sent to two endpoints is two
   * different requests.
   */
  idempotencyKey?: string;
}

/** \`Idempotency-Key\` header params, or undefined when no key was given. */
export function idempotency(options?: RequestOptions) {
  const key = options?.idempotencyKey;
  if (!key) return undefined;
  if (key.length > MAX_IDEMPOTENCY_KEY_LENGTH) {
    throw new Error(
      `Idempotency-Key must be ${MAX_IDEMPOTENCY_KEY_LENGTH} characters or fewer. ` +
        "A truncated key collides with every other key sharing its prefix, so this " +
        "throws rather than trimming."
    );
  }
  return { header: { "Idempotency-Key": key } };
}

export interface RateLimit {
  /** Requests allowed per window. */
  limit: number;
  /** Requests left in this window. */
  remaining: number;
  /** Raw \`RateLimit-Policy\`, e.g. \`120;w=60\`. */
  policy: string | null;
  /** Only on a 429. Milliseconds to wait. */
  retryAfterMs: number | null;
}

/**
 * Read the rate-limit headers off any response — success OR error.
 *
 * They are on both because the API attaches them at a single choke point. A
 * client backing off after a 429 needs them at least as much as one that
 * succeeded, and this is the ergonomic that makes them reachable without
 * narrowing the result union first.
 *
 * NOTE: the limit is a best-effort backstop against runaway loops, not a quota.
 * It is enforced per server instance, so the real ceiling across a scaled
 * deployment is higher than the advertised number. Do not build a scheduler
 * that assumes otherwise.
 */
export function rateLimit(response: Response | undefined): RateLimit | null {
  if (!response) return null;
  const limit = Number(response.headers.get("RateLimit-Limit"));
  if (!Number.isFinite(limit)) return null;
  const retryAfter = Number(response.headers.get("Retry-After"));
  return {
    limit,
    remaining: Number(response.headers.get("RateLimit-Remaining")) || 0,
    policy: response.headers.get("RateLimit-Policy"),
    retryAfterMs: Number.isFinite(retryAfter) && retryAfter > 0 ? retryAfter * 1000 : null,
  };
}

/**
 * The request id the API stamped on this response.
 *
 * Quote it in a support request — it is the only handle that ties what you saw
 * to what we logged. Errors also carry it in the body as \`request_id\`.
 */
export function requestId(response: Response | undefined): string | null {
  return response?.headers.get("X-Request-Id") ?? null;
}

/**
 * What to try when a request fails, keyed by the error code.
 *
 * Exists because "invalid_request" alone sends a developer to the wrong place.
 * Codes not listed here get null rather than a guess.
 */
export function suggestedAction(code: string): string | null {
  switch (code) {
    case "unauthorized":
      return `Check the key is current and starts with "${API_KEY_PREFIX}". Mint a new one in the dashboard if it was revoked.`;
    case "forbidden":
      return "The key is valid but its scope is too low. The error body carries required_scope and key_scope — mint a key at that tier.";
    case "not_found":
      return "Check the id, and that the key can reach that project — an org-scoped key may be limited to a subset.";
    case "rate_limited":
      return "Back off for retryAfterMs from rateLimit(response), then retry.";
    case "conflict":
      return "Something changed underneath this call. Re-read the resource and decide again.";
    case "invalid_request":
      return "The message names the offending field. Nothing was changed, so it is safe to fix and resend.";
    case "upstream_error":
      return "A provider we depend on failed. Safe to retry with backoff; pass an idempotencyKey so a retry cannot double-apply.";
    case "internal":
      return "Our fault. Quote requestId(response) in a support request.";
    default:
      return null;
  }
}

/** Timeout signal, merged with any caller-supplied signal. */
export function timeoutSignal(timeoutMs = DEFAULT_TIMEOUT_MS): AbortSignal {
  return AbortSignal.timeout(timeoutMs);
}
